swiftmailer:
    url: '%env(MAILER_URL)%'
    transport:   smtp
    username:    ""
    password:     ""
    host:   smtp.gmail.com
    port :          465
    encryption:   ssl
    auth-mode:  login
    spool: { type: 'memory' }
     
